package com.coursemonitor.entity;
// Generated Mar 28, 2016 9:57:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private int FId;
     private String FName;
     private Set managementStaffs = new HashSet(0);
     private Set staffs = new HashSet(0);

    public Faculty() {
    }

	
    public Faculty(int FId) {
        this.FId = FId;
    }
    public Faculty(int FId, String FName, Set managementStaffs, Set staffs) {
       this.FId = FId;
       this.FName = FName;
       this.managementStaffs = managementStaffs;
       this.staffs = staffs;
    }
   
    public int getFId() {
        return this.FId;
    }
    
    public void setFId(int FId) {
        this.FId = FId;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public Set getManagementStaffs() {
        return this.managementStaffs;
    }
    
    public void setManagementStaffs(Set managementStaffs) {
        this.managementStaffs = managementStaffs;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


