package com.coursemonitor.entity;
// Generated Mar 28, 2016 9:57:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private int stId;
     private Faculty faculty;
     private String stName;
     private String stEmail;
     private String stUsername;
     private String stPassword;
     private Set reportsForClId = new HashSet(0);
     private Set assignCoursesForCmId = new HashSet(0);
     private Set assignCoursesForClId = new HashSet(0);
     private Set reportsForCmId = new HashSet(0);

    public Staff() {
    }

	
    public Staff(int stId) {
        this.stId = stId;
    }
    public Staff(int stId, Faculty faculty, String stName, String stEmail, String stUsername, String stPassword, Set reportsForClId, Set assignCoursesForCmId, Set assignCoursesForClId, Set reportsForCmId) {
       this.stId = stId;
       this.faculty = faculty;
       this.stName = stName;
       this.stEmail = stEmail;
       this.stUsername = stUsername;
       this.stPassword = stPassword;
       this.reportsForClId = reportsForClId;
       this.assignCoursesForCmId = assignCoursesForCmId;
       this.assignCoursesForClId = assignCoursesForClId;
       this.reportsForCmId = reportsForCmId;
    }
   
    public int getStId() {
        return this.stId;
    }
    
    public void setStId(int stId) {
        this.stId = stId;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public String getStName() {
        return this.stName;
    }
    
    public void setStName(String stName) {
        this.stName = stName;
    }
    public String getStEmail() {
        return this.stEmail;
    }
    
    public void setStEmail(String stEmail) {
        this.stEmail = stEmail;
    }
    public String getStUsername() {
        return this.stUsername;
    }
    
    public void setStUsername(String stUsername) {
        this.stUsername = stUsername;
    }
    public String getStPassword() {
        return this.stPassword;
    }
    
    public void setStPassword(String stPassword) {
        this.stPassword = stPassword;
    }
    public Set getReportsForClId() {
        return this.reportsForClId;
    }
    
    public void setReportsForClId(Set reportsForClId) {
        this.reportsForClId = reportsForClId;
    }
    public Set getAssignCoursesForCmId() {
        return this.assignCoursesForCmId;
    }
    
    public void setAssignCoursesForCmId(Set assignCoursesForCmId) {
        this.assignCoursesForCmId = assignCoursesForCmId;
    }
    public Set getAssignCoursesForClId() {
        return this.assignCoursesForClId;
    }
    
    public void setAssignCoursesForClId(Set assignCoursesForClId) {
        this.assignCoursesForClId = assignCoursesForClId;
    }
    public Set getReportsForCmId() {
        return this.reportsForCmId;
    }
    
    public void setReportsForCmId(Set reportsForCmId) {
        this.reportsForCmId = reportsForCmId;
    }




}


